services:
  mysql:
    image: mysql:8.4
    container_name: laravel-plataforma-cursos
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: plat_cursos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: laravel-plataforma-cursos-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
